name: Pull request workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check out java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload unit test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Unit test reports
          path: '**/build/reports/*'
